# Generated by Django 5.2.14 on 2026-07-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthDailyAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hrv", "Heart-rate variability"),
                            ("resting_hr", "Resting heart rate"),
                            ("sleep_hours", "Sleep"),
                            ("bodyweight", "Bodyweight"),
                            ("steps", "Steps"),
                            ("water_ml", "Water"),
                        ],
                        max_length=24,
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "minimum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("sample_count", models.PositiveIntegerField()),
                ("source", models.CharField(max_length=64)),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField()),
                ("server_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_daily_aggregates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "kind", "source"],
                "indexes": [
                    models.Index(
                        fields=["owner", "kind", "date"],
                        name="health_heal_owner_i_5dd99b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "kind", "date", "source"),
                        name="unique_owner_health_day_source",
                    )
                ],
            },
        ),
    ]
