# Generated by Django 5.2.15 on 2026-06-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindersettings',
            name='am_label',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='night_label',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='noon_label',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='pm_label',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='waking_label',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
