# Generated by Django 5.2.14 on 2026-06-01 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        ('protocols', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phase_type', models.CharField(choices=[('bulk', 'Off-season bulk'), ('cut', 'Cut'), ('maintain', 'Maintenance'), ('recomp', 'Recomp'), ('prep', 'Contest prep'), ('cruise', 'Cruise'), ('blast', 'Blast'), ('trt', 'TRT'), ('mini_cut', 'Mini-cut'), ('other', 'Other')], default='other', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null = ongoing.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutrition_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases', to='nutrition.nutritiontarget')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases', to='training.program')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases', to='protocols.protocol')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['owner', 'start_date'], name='core_phase_owner_i_6f3553_idx')],
            },
        ),
    ]
