# Generated by Django 5.2.15 on 2026-06-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachclientlink',
            name='can_edit_prescriptions',
            field=models.BooleanField(default=True),
        ),
    ]
