# Generated by Django 5.2.15 on 2026-07-27 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_coachclientlink_can_edit_prescriptions'),
        ('diary', '0004_progressphoto_client_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_comments', to=settings.AUTH_USER_MODEL)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='diary.checkin')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['check_in', 'created_at'], name='coaching_ch_check_i_f8c16f_idx')],
            },
        ),
    ]
