# Generated by Django 5.2.14 on 2026-05-31 19:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('view', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('side', 'Side')], default='front', max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('bodyweight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('energy', models.PositiveSmallIntegerField(blank=True, help_text='Energy 1–5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sleep', models.PositiveSmallIntegerField(blank=True, help_text='Sleep quality 1–5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mood', models.PositiveSmallIntegerField(blank=True, help_text='Mood 1–5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('motivation', models.PositiveSmallIntegerField(blank=True, help_text='Motivation 1–5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('soreness', models.PositiveSmallIntegerField(blank=True, help_text='Soreness 1–5 (5 = very sore)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, help_text='Headspace, physical experience, etc.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'date'), name='uniq_checkin_owner_date')],
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taken_on', models.DateField()),
                ('object_key', models.CharField(max_length=255)),
                ('thumb_key', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(default='image/jpeg', max_length=40)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL)),
                ('pose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='diary.pose')),
            ],
            options={
                'ordering': ['-taken_on', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'pose', 'taken_on'], name='diary_progr_owner_i_4ba840_idx')],
            },
        ),
    ]
