# Generated by Django 5.2.14 on 2026-06-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="diastolic",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="pulse",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="systolic",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
