# Generated by Django 5.2.14 on 2026-05-30 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('other', 'Other')], default='other', max_length=12)),
            ],
            options={
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('bodyweight', 'Bodyweight'), ('smith', 'Smith machine'), ('kettlebell', 'Kettlebell'), ('banded', 'Resistance band'), ('other', 'Other')], default='barbell', max_length=16)),
                ('load_type', models.CharField(choices=[('weight_reps', 'Weight × reps'), ('bodyweight_reps', 'Bodyweight reps'), ('weighted_bodyweight', 'Bodyweight + added weight'), ('duration', 'Duration (e.g. plank)'), ('distance_duration', 'Distance + duration (cardio)')], default='weight_reps', max_length=24)),
                ('equipment', models.CharField(blank=True, max_length=120)),
                ('instructions', models.TextField(blank=True)),
                ('is_unilateral', models.BooleanField(default=False, help_text='Performed one side at a time (logged load is per-side).')),
                ('owner', models.ForeignKey(blank=True, help_text='Null = global/seeded exercise available to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
                ('primary_muscles', models.ManyToManyField(blank=True, related_name='primary_exercises', to='training.muscle')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='secondary_exercises', to='training.muscle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('superset_group', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='training.exercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LoggedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('superset_group', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logged_exercises', to='training.exercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LoggedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('set_type', models.CharField(choices=[('warmup', 'Warm-up'), ('working', 'Working'), ('drop', 'Drop set'), ('rest_pause', 'Rest-pause'), ('myo_rep', 'Myo-rep'), ('cluster', 'Cluster'), ('amrap', 'AMRAP'), ('backoff', 'Back-off'), ('top_set', 'Top set'), ('failure', 'To failure')], default='working', max_length=16)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rir', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_m', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('e1rm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_pr', models.BooleanField(default=False)),
                ('logged_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.loggedexercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlannedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('set_type', models.CharField(choices=[('warmup', 'Warm-up'), ('working', 'Working'), ('drop', 'Drop set'), ('rest_pause', 'Rest-pause'), ('myo_rep', 'Myo-rep'), ('cluster', 'Cluster'), ('amrap', 'AMRAP'), ('backoff', 'Back-off'), ('top_set', 'Top set'), ('failure', 'To failure')], default='working', max_length=16)),
                ('target_reps_low', models.PositiveIntegerField(blank=True, null=True)),
                ('target_reps_high', models.PositiveIntegerField(blank=True, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('target_pct_1rm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('target_rir', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo', models.CharField(blank=True, help_text="e.g. '3-1-1-0'", max_length=12)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_sets', to='training.exerciseslot')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.program')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='exerciseslot',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='training.trainingday'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('bodyweight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training.trainingday')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='loggedexercise',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_exercises', to='training.workoutsession'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_exercise_owner_name'),
        ),
    ]
