# Generated by Django 5.2.14 on 2026-06-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedset',
            name='rest_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
