# Generated by Django 5.2.14 on 2026-06-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_loggedset_rest_seconds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loggedset",
            name="rpe",
        ),
        migrations.RemoveField(
            model_name="plannedset",
            name="target_rpe",
        ),
    ]
