# Generated by Django 5.2.14 on 2026-06-14 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_remove_loggedset_rpe_remove_plannedset_target_rpe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["owner", "started_at"], name="training_wo_owner_i_843a4f_idx"
            ),
        ),
    ]
