# Generated by Django 5.2.15 on 2026-06-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_coach',
            field=models.BooleanField(default=False, help_text='Can take on clients and view their data (coaching interface).'),
        ),
    ]
