# Generated by Django 5.2.14 on 2026-06-14 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("waist", "Waist"),
                            ("neck", "Neck"),
                            ("hip", "Hip"),
                            ("chest", "Chest"),
                            ("upper_arm_left", "Upper arm (left)"),
                            ("upper_arm_right", "Upper arm (right)"),
                            ("forearm_left", "Forearm (left)"),
                            ("forearm_right", "Forearm (right)"),
                            ("thigh_left", "Thigh (left)"),
                            ("thigh_right", "Thigh (right)"),
                            ("calf_left", "Calf (left)"),
                            ("calf_right", "Calf (right)"),
                            ("body_fat", "Body fat %"),
                            ("resting_hr", "Resting heart rate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dexa", "DEXA"),
                            ("bia", "Bioimpedance"),
                            ("calipers", "Calipers"),
                            ("scale", "Smart scale"),
                            ("estimate", "Estimated"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "type"],
                "indexes": [
                    models.Index(
                        fields=["owner", "type", "date"],
                        name="analysis_bo_owner_i_8991aa_idx",
                    )
                ],
            },
        ),
    ]
