# Generated by Django 5.2.14 on 2026-05-30 21:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('energy', 'Energy'), ('macro', 'Macronutrient'), ('vitamin', 'Vitamin'), ('mineral', 'Mineral'), ('other', 'Other')], max_length=12)),
                ('unit', models.CharField(choices=[('kcal', 'kcal'), ('g', 'g'), ('mg', 'mg'), ('mcg', 'µg'), ('iu', 'IU')], max_length=8)),
                ('rda', models.DecimalField(blank=True, decimal_places=3, help_text='Reference daily amount in `unit`, used as a default micro target.', max_digits=10, null=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('is_energy', models.BooleanField(default=False, help_text='True only for calories.')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('custom', 'Custom'), ('seed', 'Seeded'), ('off', 'Open Food Facts'), ('usda', 'USDA FoodData Central')], default='custom', max_length=8)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, help_text='Null = global food available to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_100g', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_nutrients', to='nutrition.food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_nutrients', to='nutrition.nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='nutrients',
            field=models.ManyToManyField(related_name='foods', through='nutrition.FoodNutrient', to='nutrition.nutrient'),
        ),
        migrations.CreateModel(
            name='NutrientTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Daily target', max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('day_type', models.CharField(choices=[('any', 'Any day'), ('training', 'Training day'), ('rest', 'Rest day')], default='any', max_length=10)),
                ('calories', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('carb_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('micro_targets', models.ManyToManyField(related_name='targets', through='nutrition.NutrientTarget', to='nutrition.nutrient')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='nutrienttarget',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_targets', to='nutrition.nutritiontarget'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('servings', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='nutrition.food')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ServingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_default', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='nutrition.food')),
            ],
            options={
                'ordering': ['-is_default', 'grams'],
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('pre_workout', 'Pre-workout'), ('post_workout', 'Post-workout')], default='breakfast', max_length=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8)),
                ('grams', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diary_entries', to='nutrition.food')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diary_entries', to='nutrition.recipe')),
                ('serving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='nutrition.servingsize')),
            ],
            options={
                'ordering': ['date', 'meal', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='foodnutrient',
            constraint=models.UniqueConstraint(fields=('food', 'nutrient'), name='uniq_food_nutrient'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='nutrition_f_name_caa2b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='nutrienttarget',
            constraint=models.UniqueConstraint(fields=('target', 'nutrient'), name='uniq_target_nutrient'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['owner', 'date'], name='nutrition_d_owner_i_55067f_idx'),
        ),
    ]
