# Generated by Django 5.2.14 on 2026-06-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_meal_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="unit",
            field=models.CharField(
                choices=[("g", "g"), ("ml", "ml")], default="g", max_length=4
            ),
        ),
    ]
