# Generated by Django 5.2.15 on 2026-07-02 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_nutrient_target_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiontarget',
            name='water_ml',
            field=models.PositiveIntegerField(blank=True, help_text='Daily hydration goal in millilitres.', null=True),
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount_ml', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('manual', 'Logged in app'), ('healthkit', 'Apple Health')], default='manual', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['owner', 'date'], name='nutrition_w_owner_i_5e9bb0_idx')],
            },
        ),
    ]
