# Generated by Django 5.2.14 on 2026-05-31 09:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('hormone', 'Hormone'), ('lipid', 'Lipid'), ('liver', 'Liver'), ('kidney', 'Kidney'), ('blood', 'Blood count'), ('metabolic', 'Metabolic'), ('other', 'Other')], default='other', max_length=12)),
                ('ref_low', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ref_high', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ref_low_male', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ref_high_male', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ref_low_female', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ref_high_female', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InjectionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('region', models.CharField(choices=[('glute', 'Glute (dorsogluteal)'), ('ventroglute', 'Ventrogluteal'), ('quad', 'Quad (vastus lateralis)'), ('delt', 'Deltoid'), ('lat_delt', 'Lateral delt (SubQ)'), ('abdomen', 'Abdomen (SubQ)'), ('pec', 'Pec'), ('bicep', 'Biceps'), ('tricep', 'Triceps'), ('calf', 'Calf')], max_length=12)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=8)),
                ('x', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=5)),
                ('y', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=5)),
            ],
            options={
                'ordering': ['region', 'side'],
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('compound_class', models.CharField(choices=[('anabolic', 'Anabolic steroid'), ('peptide', 'Peptide'), ('sarm', 'SARM'), ('ancillary', 'Ancillary / pharmaceutical'), ('other', 'Other')], default='other', max_length=12)),
                ('default_unit', models.CharField(choices=[('mg', 'mg'), ('mcg', 'µg'), ('iu', 'IU'), ('ml', 'ml'), ('tablet', 'tablet'), ('capsule', 'capsule')], default='mg', max_length=8)),
                ('default_route', models.CharField(choices=[('im', 'Intramuscular'), ('subq', 'Subcutaneous'), ('oral', 'Oral'), ('topical', 'Topical'), ('nasal', 'Nasal'), ('other', 'Other')], default='im', max_length=8)),
                ('half_life_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Elimination half-life in hours (for concentration modelling).', max_digits=9, null=True)),
                ('ester', models.CharField(blank=True, max_length=40)),
                ('active_fraction', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Fraction of dose that is active drug (ester/salt weight correction).', max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null = global/seeded compound available to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('is_active', models.BooleanField(default=False)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('serving_label', models.CharField(default='1 serving', max_length=80)),
                ('target_benefit', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dose_unit', models.CharField(choices=[('mg', 'mg'), ('mcg', 'µg'), ('iu', 'IU'), ('ml', 'ml'), ('tablet', 'tablet'), ('capsule', 'capsule')], default='mg', max_length=8)),
                ('route', models.CharField(blank=True, choices=[('im', 'Intramuscular'), ('subq', 'Subcutaneous'), ('oral', 'Oral'), ('topical', 'Topical'), ('nasal', 'Nasal'), ('other', 'Other')], max_length=8)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('eod', 'Every other day'), ('2x_week', '2× / week'), ('3x_week', '3× / week'), ('weekly', 'Weekly'), ('2x_day', '2× / day'), ('prn', 'As needed')], default='weekly', max_length=8)),
                ('target_benefit', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protocol_items', to='protocols.compound')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='protocols.protocol')),
                ('supplement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protocol_items', to='protocols.supplement')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taken_at', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('mg', 'mg'), ('mcg', 'µg'), ('iu', 'IU'), ('ml', 'ml'), ('tablet', 'tablet'), ('capsule', 'capsule')], default='mg', max_length=8)),
                ('route', models.CharField(blank=True, choices=[('im', 'Intramuscular'), ('subq', 'Subcutaneous'), ('oral', 'Oral'), ('topical', 'Topical'), ('nasal', 'Nasal'), ('other', 'Other')], max_length=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('side_effects', models.CharField(blank=True, max_length=255)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dose_logs', to='protocols.compound')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to=settings.AUTH_USER_MODEL)),
                ('injection_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dose_logs', to='protocols.injectionsite')),
                ('protocol_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dose_logs', to='protocols.protocolitem')),
                ('supplement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dose_logs', to='protocols.supplement')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplementNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_serving', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplement_nutrients', to='nutrition.nutrient')),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_nutrients', to='protocols.supplement')),
            ],
        ),
        migrations.AddField(
            model_name='supplement',
            name='nutrients',
            field=models.ManyToManyField(related_name='supplements', through='protocols.SupplementNutrient', to='nutrition.nutrient'),
        ),
        migrations.CreateModel(
            name='Vial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('concentration_mg_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('unit', models.CharField(choices=[('mg', 'mg'), ('mcg', 'µg'), ('iu', 'IU'), ('ml', 'ml'), ('tablet', 'tablet'), ('capsule', 'capsule')], default='ml', max_length=8)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vials', to='protocols.compound')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['compound__name', 'label'],
            },
        ),
        migrations.CreateModel(
            name='BloodPressureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('systolic', models.PositiveIntegerField()),
                ('diastolic', models.PositiveIntegerField()),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('measured_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['owner', 'measured_at'], name='protocols_b_owner_i_bf0ea5_idx')],
            },
        ),
        migrations.CreateModel(
            name='BloodResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('measured_on', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='protocols.bloodmarker')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_on'],
                'indexes': [models.Index(fields=['owner', 'marker', 'measured_on'], name='protocols_b_owner_i_d12173_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='compound',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_compound_owner_name'),
        ),
        migrations.AddIndex(
            model_name='doselog',
            index=models.Index(fields=['owner', 'taken_at'], name='protocols_d_owner_i_6d76e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplementnutrient',
            constraint=models.UniqueConstraint(fields=('supplement', 'nutrient'), name='uniq_supplement_nutrient'),
        ),
        migrations.AddConstraint(
            model_name='supplement',
            constraint=models.UniqueConstraint(fields=('owner', 'name', 'brand'), name='uniq_supp_owner_name'),
        ),
    ]
