# Generated by Django 5.2.14 on 2026-06-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocols", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolitem",
            name="days_of_week",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="protocolitem",
            name="times_of_day",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="protocolitem",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("eod", "Every other day"),
                    ("every_3_days", "Every 3 days"),
                    ("weekly", "Weekly"),
                    ("specific_days", "Specific days of week"),
                    ("prn", "As needed"),
                    ("2x_week", "2× / week"),
                    ("3x_week", "3× / week"),
                    ("2x_day", "2× / day"),
                ],
                default="weekly",
                max_length=16,
            ),
        ),
    ]
