# Generated by Django 5.2.14 on 2026-06-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocols", "0002_item_scheduling"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodmarker",
            name="aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bloodresult",
            name="ref_high",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="bloodresult",
            name="ref_low",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="bloodresult",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("pdf", "PDF import")],
                default="manual",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="bloodresult",
            name="unit",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
