# Generated by Django 5.2.14 on 2026-06-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocols", "0003_bloodmarker_aliases_bloodresult_ref_high_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doselog",
            name="status",
            field=models.CharField(
                choices=[("taken", "Taken"), ("skipped", "Skipped")],
                default="taken",
                help_text="'skipped' = intentionally not taken (e.g. a sick day).",
                max_length=8,
            ),
        ),
    ]
