# Generated by Django 5.2.14 on 2026-06-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocols", "0004_doselog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compound",
            name="default_unit",
            field=models.CharField(
                choices=[
                    ("mg", "mg"),
                    ("mcg", "µg"),
                    ("iu", "IU"),
                    ("ml", "ml"),
                    ("tablet", "tablet"),
                    ("capsule", "capsule"),
                    ("serving", "serving"),
                ],
                default="mg",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="doselog",
            name="unit",
            field=models.CharField(
                choices=[
                    ("mg", "mg"),
                    ("mcg", "µg"),
                    ("iu", "IU"),
                    ("ml", "ml"),
                    ("tablet", "tablet"),
                    ("capsule", "capsule"),
                    ("serving", "serving"),
                ],
                default="mg",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="protocolitem",
            name="dose_unit",
            field=models.CharField(
                choices=[
                    ("mg", "mg"),
                    ("mcg", "µg"),
                    ("iu", "IU"),
                    ("ml", "ml"),
                    ("tablet", "tablet"),
                    ("capsule", "capsule"),
                    ("serving", "serving"),
                ],
                default="mg",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="vial",
            name="unit",
            field=models.CharField(
                choices=[
                    ("mg", "mg"),
                    ("mcg", "µg"),
                    ("iu", "IU"),
                    ("ml", "ml"),
                    ("tablet", "tablet"),
                    ("capsule", "capsule"),
                    ("serving", "serving"),
                ],
                default="ml",
                max_length=8,
            ),
        ),
    ]
