# Generated by Django 5.2.14 on 2026-06-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocols", "0005_alter_compound_default_unit_alter_doselog_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="bioavailability",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Fraction absorbed (0–1); treated as 1 when unknown.",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compound",
            name="pk_source",
            field=models.TextField(
                blank=True,
                help_text="Source(s) for the half-life / Tmax / bioavailability values.",
            ),
        ),
        migrations.AddField(
            model_name="compound",
            name="tmax_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Time to peak (hours) — drives the absorption phase of the curve.",
                max_digits=9,
                null=True,
            ),
        ),
    ]
