# Generated by Django 5.2.14 on 2026-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocols", "0006_compound_bioavailability_compound_pk_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="injectionsite",
            name="route",
            field=models.CharField(
                choices=[
                    ("im", "Intramuscular"),
                    ("subq", "Subcutaneous"),
                    ("oral", "Oral"),
                    ("topical", "Topical"),
                    ("nasal", "Nasal"),
                    ("other", "Other"),
                ],
                default="im",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="injectionsite",
            name="region",
            field=models.CharField(
                choices=[
                    ("glute", "Glute"),
                    ("ventroglute", "Ventrogluteal"),
                    ("quad", "Quad"),
                    ("delt", "Deltoid"),
                    ("front_delt", "Front delt"),
                    ("rear_delt", "Rear delt"),
                    ("lat_delt", "Lateral delt (SubQ)"),
                    ("lats", "Lats"),
                    ("pec", "Pec / chest"),
                    ("abdomen", "Abdomen (SubQ)"),
                    ("lower_back", "Lower back"),
                    ("lower_belly", "Lower belly"),
                    ("bicep", "Biceps"),
                    ("tricep", "Triceps"),
                    ("calf", "Calf"),
                ],
                max_length=12,
            ),
        ),
    ]
